/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Feedback = IDL.Record({
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ContactInfo = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getAllLeads' : IDL.Func([], [IDL.Vec(ContactInfo)], ['query']),
  'getStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'finesSaved' : IDL.Nat,
          'incomeGenerated' : IDL.Nat,
          'users' : IDL.Nat,
          'wasteRecycled' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'submitFeedback' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [IDL.Bool], []),
  'submitLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Feedback = IDL.Record({
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ContactInfo = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getAllLeads' : IDL.Func([], [IDL.Vec(ContactInfo)], ['query']),
    'getStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'finesSaved' : IDL.Nat,
            'incomeGenerated' : IDL.Nat,
            'users' : IDL.Nat,
            'wasteRecycled' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'submitFeedback' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [IDL.Bool], []),
    'submitLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };