/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactInfo {
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface Feedback {
  'name' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface _SERVICE {
  'getAllFeedback' : ActorMethod<[], Array<Feedback>>,
  'getAllLeads' : ActorMethod<[], Array<ContactInfo>>,
  'getStats' : ActorMethod<
    [],
    {
      'finesSaved' : bigint,
      'incomeGenerated' : bigint,
      'users' : bigint,
      'wasteRecycled' : bigint,
    }
  >,
  'submitFeedback' : ActorMethod<[string, string, bigint], boolean>,
  'submitLead' : ActorMethod<[string, string, string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];